export const root = {
burger: document.getElementById("burger"),
searchBut: document.getElementById("search-button"),
sidebar: document.getElementById("sidebar-menu"),
closeBtn: document.getElementById("close-menu"),
searchBox: document.getElementById("sidebar-search"),
modal: document.getElementById('modal'),
openModalBtn: document.getElementById('openModalBtn'),
closeModalBtn: document.querySelector('.modal__cancel'),
btn: document.getElementById('submit'),
text: document.querySelector('.modal__message'),
content: document.querySelector('.modal__content'),
closeModalBtn:document.querySelector('.modal__cancel'),
log: document.querySelector('.header__registration'),
modal: document.querySelector('.modal'),
form: document.getElementById('form'),
inputs: form.querySelectorAll('input'),
log: document.querySelector('.header__registration'),
addressInput: document.getElementById('adress'),
submitBtn: document.getElementById('submit'),
iconUser: document.querySelector('.header__user'), 
userInput: document.getElementById('first'),
nameInput: document.getElementById('last'),
emailInput: document.getElementById('email'),
phoneInput: document.getElementById('tel'),
passwordInput: document.getElementById('password')
}
 