export const root = {
burger: document.getElementById("burger"),
searchBut: document.getElementById("search-button"),
sidebar: document.getElementById("sidebar-menu"),
closeBtn: document.getElementById("close-menu"),
searchBox: document.getElementById("sidebar-search"),
modal: document.getElementById('modal'),
openModalBtn: document.getElementById('openModalBtn'),
closeModalBtn: document.querySelector('.modal__cancel'),
btn: document.getElementById('submit'),
text: document.querySelector('.modal__message'),
content: document.querySelector('.modal__content'),
closeModalBtn:document.querySelector('.modal__cancel'),
log: document.querySelector('.header__registration'),
modal: document.querySelector('.modal'),
form: document.getElementById('form'),
inputs: form.querySelectorAll('input'),
log: document.querySelector('.header__registration'),
submitBtn: document.getElementById('submit'),
iconUser: document.querySelector('.header__user'), 
emailInput: document.getElementById('email'),
passwordInput: document.getElementById('password'),
cartContent: document.getElementById('content'),
cartButton: document.querySelector('.header__info-cart'),
cartQuantity: document.querySelector('.cart-item__quantity-num'),
cartBody: document.querySelector('.cart'),
cartOrder: document.querySelector('.cart-item__order'),
cartNum: document.querySelector('.header__cart-count span'),
cartOrderCont: document.querySelector('.cart-item__order-cont')
}
 